### ISSUE TITLE
Integrate ModelCropper

### ISSUE THREAD

**Issue by jcfr** [Slicer/SlicerSurfaceToolbox#2]
The idea would be to remove the corresponding extension and integrate the feature in SlicerSurfaceToolbox.  See details at https://github.com/Slicer/ExtensionsIndex/pull/1654#issuecomment-510974269

**Comment by lassoan** [comment]
Clip with region is added to Dynamic modeler module. It can clip surfaces dynamically and supports the new Markups ROI node, so probably ModelCropper extension is not needed anymore.
