### ISSUE TITLE
Preserve surface normals when cutting planes in dynamic modeller

### ISSUE THREAD

**Issue by lassoan** [Slicer/SlicerSurfaceToolbox#25]
Currently, plane cut rule in dynamic modeller removes surface normals. The best would be to preserve the original normals, as in some cases normal computation on a clipped surfaces might not be robust (clipped surfaces may get flipped as there is no clear inside/outside face anymore).

**Comment by lassoan** [comment]
Thanks, this commit is good as a quick workaround, but unfortunately we cannot use vtkPolyDataNormals reliably in a cut surface. It will randomly compute inverted normals because there is no way you can tell from an open surface which direction was inside/outside.

Since append filter only keeps scalars that are present in all inputs, we need to manually add point normals to the generated plane (it is a constant - the plane normal direction).

**Comment by Sunderlandkyl** [comment]
I tried that originally, but I found that the append filter kept discarding my manually generated normals. Perhaps I missed something, I'll try it again.

**Comment by lassoan** [comment]
It should work. Maybe not the same array type (float/double) was used? Or maybe there is a bug in VTK, but it is not very likely (and we can fix it anyway, it it was the case).

**Comment by Sunderlandkyl** [comment]
This was fixed in https://github.com/Slicer/SlicerSurfaceToolbox/pull/28.
