### ISSUE TITLE
Turn off CapSurface for plane cut

### ISSUE THREAD

**Issue by che85** [Slicer/SlicerSurfaceToolbox#43]
Hello, 

is there a way to turn off capping when using the vtkMRMLDynamicModelerNode through scripting? 

I couldn't find a parameter a Python accessible parameter for doing that.

**Comment by Sunderlandkyl** [comment]
Dynamic modeler nodes currently use node attributes to set parameters.
You can change the cap setting using the "CapParameter" attribute:

```planeCutNode.SetAttribute("CapSurface", "0")```

**Comment by che85** [comment]
Awesome. Thank you.
