### ISSUE TITLE
Dynamic Modeler Curve Cut inside model doesn't work when the model has islands

### ISSUE THREAD

**Issue by Connor-Bowley** [Slicer/SlicerSurfaceToolbox#45]
Given a model with islands and a markups curve completely on one of the islands
When a Dynamic Modeler Curve Cut is made
Then I would expect the inside model to be the cutout of markups curve and the island it is on.

Currently the inside model will be the largest closed island of the model, even if it is completely separated from the input curve. I believe the issue is at the vtkConnectivityFilter and the fact it defaults to getting the largest region.

Example:
![With annotations](https://user-images.githubusercontent.com/14840636/138761025-7044cdfd-0f3b-457e-b455-49a4a732051a.png)

**Comment by lassoan** [comment]
This has been fixed by completely reworking the underlying VTK filter.

![image](https://user-images.githubusercontent.com/307929/192678397-5b327a89-4e32-4bd9-835e-838289e65811.png)
