### ISSUE TITLE
Failed to build on macOS

### ISSUE THREAD

**Issue by jamesobutler** [Slicer/SlicerSurfaceToolbox#47]
Slicer factory build failed on macOS due to recent updates to SlicerSurfaceToolbox (https://github.com/Slicer/SlicerSurfaceToolbox/commit/3e4245303e1d1599d4ef514373711598d6bd62c6). This is preventing the Slicer macOS build from completing successfully and therefore preventing macOS extensions from being built as well.

https://slicer.cdash.org/viewBuildError.php?buildid=2459187

**Comment by lassoan** [comment]
Fixed in https://github.com/Slicer/SlicerSurfaceToolbox/commit/8dd9ce0532dcb5e5c5f50d095bd15954192d02cb

**Comment by jcfr** [comment]
To follow up, macOS error will effectively be fixed by #48

**Comment by lassoan** [comment]
Thanks a lot @jcfr for all the improvements!
